name: News Aggregator Bot

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    # --- הוספה חדשה ---
    # הבלוק הזה מעניק ל-Action הרשאה לכתוב קבצים בחזרה למאגר.
    permissions:
      contents: write
    # ------------------

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the Python script
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: python main.py

    - name: Commit seen links file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add seen_links.txt
        git diff --quiet && git diff --staged --quiet || git commit -m "Update seen links"
        git push
